default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["POSTGRESQL_HOST"] || "localhost" %>
  database: <%= ENV["POSTGRESQL_DB"] %>
  username: <%= ENV["POSTGRESQL_USER"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>

development:
  <<: *default
  database: dorsale_development

test: &test
  <<: *default
  database: dorsale_test

production: &production
  <<: *default

staging:
  <<: *production

cucumber:
  <<: *test
